package de.itemis.mps.forms.sandboxlang.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Address = 0;
  public static final int ChineseAddress = 1;
  public static final int Customer = 2;
  public static final int GermanAddress = 3;
  public static final int Item = 4;
  public static final int Order = 5;
  public static final int OrderedItem = 6;
  public static final int RootNode = 7;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x11d2696e04842L, 0x8ea14b4df566b650L);
    builder.put(0x6b9006747fdafadfL, Address);
    builder.put(0x6b9006747fdafcfdL, ChineseAddress);
    builder.put(0x6b9006747fdaa35eL, Customer);
    builder.put(0x6b9006747fdafae0L, GermanAddress);
    builder.put(0x6b9006747fdaa57cL, Item);
    builder.put(0x6b9006747fdaa57bL, Order);
    builder.put(0x6b9006747fdaa633L, OrderedItem);
    builder.put(0x6b9006747fdaa6e8L, RootNode);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
