package de.itemis.mps.forms.sandboxlang.editor;

/*Generated by MPS */

import jetbrains.mps.openapi.editor.cells.EditorCell;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.cellLayout.CellLayout_Horizontal;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.RoundRectangle2D;
import java.awt.Color;
import java.awt.BasicStroke;

public class TextFieldBuilder {
  public static EditorCell build(final EditorCell propertyCell) {
    EditorCell_Collection wrapper = new EditorCell_Collection(propertyCell.getContext(), propertyCell.getSNode(), new CellLayout_Horizontal()) {
      @Override
      protected void relayoutImpl() {
        super.relayoutImpl();
        int padding = 3;
        propertyCell.moveTo(getX() + padding, getY() + padding);
        propertyCell.relayout();
        setWidth(getWidth() + padding);
        setHeight(getHeight() + padding * 2);
      }

      @Override
      protected void paintBackground(Graphics g) {
        super.paintBackground(g);

        Graphics2D g2 = ((Graphics2D) g.create());
        try {
          RoundRectangle2D.Double rr = new RoundRectangle2D.Double(getX(), getY(), getWidth(), getHeight(), 3, 3);
          g2.setColor(Color.WHITE);
          g2.fill(rr);
        } finally {
          g2.dispose();
        }

      }

      @Override
      public void paintDecorations(Graphics g) {
        super.paintDecorations(g);

        Graphics2D g2 = ((Graphics2D) g.create());
        try {
          RoundRectangle2D.Double rr = new RoundRectangle2D.Double(getX(), getY(), getWidth(), getHeight(), 3, 3);
          g2.setColor(Color.BLACK);
          g2.setStroke(new BasicStroke(1.0f));
          g2.draw(rr);
        } finally {
          g2.dispose();
        }

      }
    };
    wrapper.addEditorCell(propertyCell);

    return wrapper;
  }
}
